AWSTemplateFormatVersion: '2010-09-09'
Transform: "AWS::Serverless-2016-10-31"

Parameters:
  TopicArn:
    Type: String
  OriginFileName:
    Type: String
  OriginBucket:
    Type: String
  OriginRegion:
    Type: String
  TargetBucket:
    Type: String
  TargetRegion:
    Type: String
  Password:
    Type: String
  
Resources:
  App:
    Type: AWS::Serverless::Function
    Properties:
      Handler: move-to-s3
      Runtime: go1.x
      CodeUri: build
      Timeout: 120
      #Events:
      #  SNSTrigger:
      #    Type: SNS
      #    Properties:
      #      Topic: !Ref TopicArn
      Environment:
        Variables:
          ORIGIN_FILENAME: !Ref OriginFileName
          ORIGIN_BUCKET: !Ref OriginBucket
          ORIGIN_REGION: !Ref OriginRegion
          TARGET_BUCKET: !Ref TargetBucket
          TARGET_REGION: !Ref TargetRegion
          PASSWORD: !Ref Password
